name: Semgrep CI
on:
 pull_request:
   paths:
     - '*.js'
     - '*.jsx'
jobs:
 semgrep:
   runs-on: ubuntu-latest
   container:
     image: returntocorp/semgrep:latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
       with:
         fetch-depth: 0
     - name: Run Semgrep
       run: |
         semgrep --config p/r2c --baseline-commit HEAD~ --json | jq -r '.results[] | "\(.path):\(.start.line) >>>\n \(.extra.message)"' > issues.txt
     - name: Get issues
       id: issues
       run: echo ::set-output name=issues::$(cat issues.txt)
     - name: Comment on PR
       uses: thollander/actions-comment-pull-request@v1
       with:
         message: "Semgrep found some issues:\n${{ steps.issues.outputs.issues }}"
         repo-token: ${{ secrets.GITHUB_TOKEN }}
     
